apiVersion: apps/v1
kind: Deployment                         # Un deployment es un template para crear pods
metadata:
  name: nginx-deploy
spec:
  selector:
    matchLabels:
      role: tutorial-nginx
  replicas: 2                             # Cantidad de pods que queremos en nuestro deployment
  template:
    metadata:
      labels:
        role: tutorial-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
        - name: MI_VARIABLE
          value: "yach"
        - name: MI_OTRA_VARIABLE
          value: "yach2"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 80