apiVersion: v1
kind: Service
metadata:
  name: template-frontend-service
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    app: template-frontend
status:
  loadBalancer:    