apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-frontend-deployment
  labels:
    app: template-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-frontend
  template:
    metadata:
      labels:
        app: template-frontend
    spec:
      containers:
      - name: template-frontend
        imagePullPolicy: Never              # Kubelet intentará obtener la imagen localmente de alguna manera, de lo contrario el inicio fallará
        image: template-aiprism:0.1      # Agregar la ruta o la dirección del dockerfile
        ports:
          - containerPort: 80
