apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:                                  # environment variables
    - name: MI_VARIABLE
      value: "pelado"
    - name: MI_OTRA_VARIABLE
      value: "pelade"
    - name: DD_AGENT_HOST                 # Creamos una variable de entorno con ese nombre
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP        # valor de la ip del host y que la guarde en una variable de entorno del pod
    resources:                            # asignación de recursos al contenedor no al pod
      requests:                           # recursos minimos que le vamos a dar al contenedor
        memory: "64Mi"
        cpu: "200m"
      limits:                             # recursos limite
        memory: "128Mi"
        cpu: "500m"
    readinessProbe:                       # le dice a k8s que tu pod esta listo para recibir trafico
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
    ports:
    - containerPort: 80