apiVersion: apps/v1
kind: StatefulSet             # es una forma de deployment pero con la ventaja de que crea un volumen
metadata:                     # sirve para bbdd, si quieres una bbdd en un pod tienes que correrlo con StatefulSet
  name: my-csi-app-set        # de esta forma ese volumen va a estar atado a ese pod y nunca vas a perder los datos
spec:
  selector:
    matchLabels:
      app: mypod
  serviceName: "my-frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: mypod
    spec:                     # 2ºspec, template de los pods que tiene que crear
      containers:
      - name: my-frontend
        image: busybox
        args:
        - sleep
        - infinity
        volumeMounts:         # monataje del volumen
        - mountPath: "/data"
          name: csi-pvc
  volumeClaimTemplates:
  - metadata:
      name: csi-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: do-block-storage # es un driver de k8s para un proveedor. te permite crear un volumen desde k8s en digitalOcean por ejemplo.