apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      role: hello
  template:
    metadata:
      labels:
        role: hello               # le agregamos una label que tenga como nombre role con el valor hello
    spec:
      containers:
      - name: hello               # aqui creamos un contendor que se llama hello
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello                   # nombre del servicio
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:                   # esta parte es la parte que va a redireccionar el trafico a aquellos pods que tengan esta label
    role: hello               # cada pod tiene su IP, y cambia cada vez que muere, por eso no podemos estar apuntando de un contenedor a otro
                              # o de un pod a otro usando la IP del pod. Por ello creamos un servicio que siempre va a tener la misma IP
                              # y va a encontrar el pod a traves de eso